services:
  gachagacha:
    image: ${{ secrets.DOCKER_USERNAME }}/gachagacha:latest
    container_name: gachagacha
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - gachagacha-uploads:/uploads
    depends_on:
      - redis

  redis:
    image: bitnami/redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  gachagacha-uploads:
