spring:
  config:
    import:
      - rdb.yml
      - redis.yml
      - common.yml
server:
  port: 8080
  ssl.key-store: classpath:keystore.p12 # ${SSL_KEY_STORE}
  ssl.key-store-type: PKCS12 # ${SSL_KEY_STORE_TYPE}
  ssl.key-store-password: gacha!*!* # ${SSL_KEY_STORE_PASSWORD}
  tomcat:
    threads:
      max: 3
    max-connections: 4
jwt:
  secret: weinfeglinqelrgknerkgkrkrxsatbbdddzxiowklh # ${JWT_SECRET}
file:
  profile: /uploads/profile/
image:
  api:
    endpoints:
      items: /image/items/
      backgrounds: /image/backgrounds/
  default:
    profile: default_profile.png
oauth:
  github:
    client_id: ${OAUTH_GITHUB_CLIENT_ID}
    client_secret: ${OAUTH_GITHUB_CLIENT_SECRET}
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_url: ${KAKAO_REDIRECT_URL}
    admin_key: ${KAKAO_ADMIN_KEY}

---
spring.config.activate.on-profile: local

client:
  address: http://localhost:3000

---
spring.config.activate.on-profile: dev

client:
  address: http://localhost:3000
springdoc:
  packages-to-scan: gachagacha.gachaapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alph
    path: /

---
spring.config.activate.on-profile: prod

client:
  address: http://localhost:3000
springdoc:
  packages-to-scan: gachagacha.gachaapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alph
    path: /
